version: 0.1
phases:
  build:
    commands:
      - pip install elasticsearch
  install:
    commands:
      - aws cloudformation package --template-file samTemplate.yml --s3-bucket hw2-ai2442-lambdas --output-template-file outputsamtemplate.yml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputsamtemplate.yml
