AWSTemplateFormatVersion: 2010-09-09
Description: Cloudformation Stack for HW2
Transform: "AWS::Serverless-2016-10-31"
Resources:
  cfindexphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 10
      Role: 'arn:aws:iam::811656154701:role/service-role/index-photos-role-42phqgin'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:Put'
        Api1:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
  Bucket1:
    Type: 'AWS::S3::Bucket'


  cfuploads3:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::811656154701:role/service-role/upload-s3-role-9hu7g15y'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /upload
            Method: POST
        Api2:
          Type: Api
          Properties:
            Path: /upload
            Method: PUT
            
            
  cfsearchphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 10
      Role: 'arn:aws:iam::811656154701:role/service-role/search-photos-role-woro4uc2'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /search
            Method: GET
